leondev:
  client:
    address:
      url: 'http://localhost:8082/address'

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: example
      database: cleanarch
